sfinae :sfinae.cpp
	g++ -std=c++14 -Wall -Wextra -Wconversion -Wsign-conversion -Wlogical-op -Wdouble-promotion -g -std=c++14 -Ofast -o sfinae sfinae.cpp

traits :traits.cpp
	g++ -std=c++14 -Wall -Wextra -Wconversion -Wsign-conversion -Wlogical-op -Wdouble-promotion -g -std=c++14 -Ofast -o traits traits.cpp 

iterator :iterator.cpp
	g++ -std=c++14 -Wall -Wextra -Wconversion -Wsign-conversion -Wlogical-op -Wdouble-promotion -g -std=c++14 -Ofast -o iterator iterator.cpp 

	
all : iterator traits sfinae